### ISSUE TITLE
TypeError in raise

### ISSUE THREAD

**Issue by tsgit** [inspirehep/invenio#11]
current prod gives

TypeError: exceptions must be old-style classes or derived from BaseException, not str (websearch_webinterface.py:1055:**call**)

this is still true for latest  websearch_webinterface.py in new-prod branch on line 1121

**Comment by tsgit** [comment]
https://github.com/inspirehep/invenio/blob/new-prod/modules/websearch/lib/websearch_webinterface.py#L1120-1121

**Comment by kaplun** [comment]
I guess we can happily re-raise, here, rather than `raise repr(v)`... (I wonder what was the intended meaning of this...)

**Comment by kaplun** [comment]
Moved to inveniosoftware/invenio#2084
