### ISSUE TITLE
author name search for accented characters

### ISSUE THREAD

**Issue by tsgit** [inspirehep/invenio#126]
After talking to Tibor last week I open this as an inspire issue rather than an invenio issue, although after looking at mysql/mariadb collation tables for a while I think it may still be an invenio issue.

search (in particular author names) relies on mysql collation sequence to map accented characters to their ascii counterparts for some code points from the latin1-extended block. however, there are exceptions. for example the Danish ø is not mapped to o in any utf8_\* collation table I could find in current production version of mariadb.  uft8_general_ci, utf8_bin_ci, utf8_unicode_ci, utf8_danish_ci, utf8_swedish_ci, etc.

by default Inspire is using utf8_general_ci at the moment, and this has another problem with s == ß instead of the desired ss == ß as utf8_unicode_ci would give, see https://app.asana.com/0/2691557432415/13851466396722.

therefore the searches "f a Sogaard, M" and "f a Søgaard, M" return complementary results instead of the union of both. the expected behavior is to return all records with either spelling "o" or "ø"

the simple author WORD search operates this way, e.g.: "f a Sogaard and 001:1261811" but when a first initial or full firstname is specified the PHRASE index is used and strip_accents() is not applied in BibIndexAuthorTokenizer to the PHRASE index.

Tibor suggested to apply strip_accent() to all indices and all searches. I'm unsure as to what the side effects of that would be.

T.

**Comment by kaplun** [comment]
I second Tibor in that the author index is inherently fuzzy and we can therefore take the risk of matching more than less. strip_accents() is nowadays used in the default tokenizer and in several other places, and I don't think this is going to harm to also do it in the author index (exactauthor is different)

``` python
In [1]: from invenio.textutils import strip_accents

In [2]: strip_accents("Sogaard, M")
Out[2]: 'Sogaard, M'

In [3]: strip_accents("Søgaard, M")
Out[3]: 'Sogaard, M'
```

**Comment by kaplun** [comment]
Alternatively:

``` python
In [7]: from invenio.textutils import translate_to_ascii
In [11]: translate_to_ascii("s ss ß Søgaard")
Out[11]: ['s ss ss Sogaard']
```

**Comment by kaplun** [comment]
What do you think? Shall we simply index asciified the author?

**Comment by tsgit** [comment]
http://www.unicode.org/reports/tr10/#Asymmetric_Search

when I search Müller  I want to find Mueller but not Muller. that's the finer points of language specific equivalences and asymmetric search.

anyhow, I think ascifying everything in the author tokenizer is fine -- it already does that in the author WORD tokenizer, but you have to also ascify the search terms for author. in a goggle style search, how do you decide what to ascify?

T

**Comment by tsgit** [comment]
PS: I commenting on search term ascification, because I did a quick check a while back and extended the author tokenizer to ascify everything and then the search for Søgaard found nothing in my test.

**Comment by tsgit** [comment]
also  http://userguide.icu-project.org/collation/icu-string-search-service

**Comment by kaplun** [comment]
> anyhow, I think ascifying everything in the author tokenizer is fine -- it already does that in the author WORD tokenizer, but you have to also ascify the search terms for author. in a goggle style search, how do you decide what to ascify?

Well, afterall, the Google-like search is fuzzy by definition, it already use stemming and other normalization. Shall we simply go to asciifyit all?

In the end only exact\* fields do not need to be asciified...

**Comment by tsgit** [comment]
Note: suggested solution is to upgrade to mariadb 10 and use utf8_unicode_520_ci
see 
https://app.asana.com/0/search/22319254233966/13851466396722

T.

**Comment by kaplun** [comment]
Although it wouldn't solve the:

``` sql
+------------------------------------+
| 's' = 'ß' COLLATE utf8_general_ci  |
+------------------------------------+
|                                  1 |
+------------------------------------+
1 row in set (0.00 sec)

+----------------------------------------+
| 's' = 'ß' COLLATE utf8_unicode_520_ci  |
+----------------------------------------+
|                                      0 |
+----------------------------------------+
1 row in set (0.00 sec)
```

But if I am not mistaken, @tiborsimko, this is taken care already at the Python level?

**Comment by kaplun** [comment]
So I have deployed MariaDB 10 and enable utf8_unicode_520_ci collation for the author index. It is being rebuilt right now, so, at the moment, only the "idxWORD" part is almost populated but it looks already awesome :-D

https://inspireheptest.cern.ch/search?p=author%3AS%C3%B8gaard

https://inspireheptest.cern.ch/search?p=author%3ASogaard

**Comment by kaplun** [comment]
I am about to :cry:. `utf8_unicode_520_ci` does not solve the issue for the Polish `Łł`. These are not equivalent to `Ll`.

**Comment by tsgit** [comment]
I think this in now resolved (including polish l) in inspire production?

**Comment by kaplun** [comment]
Yes. Polish l is explicitly treated on Python side.
