### ISSUE TITLE
redis hardwired into bibrank

### ISSUE THREAD

**Issue by tsgit** [inspirehep/invenio#19]
CFG_WEBSESSION_STORAGE has two options, 'redis' and 'mysql'

so that invenio can be run without redis, however 

   modules/bibrank/lib/bibrank_citation_searcher.py

has redis use hardwired and inspirehep/invenio won't run without an available redis server.

Seems to me that bibrank either should inherit from CFG_WEBSESSION_STORAGE or have its own setting to select caching engine

Cheers
T.

**Comment by Osso** [comment]
Indeed, I had a fallback but it is not working properly. I'll have a look.

**Comment by kaplun** [comment]
Moved to inveniosoftware/invenio#2083
