### ISSUE TITLE
search problem with negation and boolean or 

### ISSUE THREAD

**Issue by tsgit** [inspirehep/invenio#216]
negation isn't properly commutative

In [31]: len(perform_request_search(p='-author:"catelan, m" | salamanca'))
1094167

In [32]: len(perform_request_search(p='salamanca | -author:"catelan, m"'))
1082

See https://rt.inspirehep.net/Ticket/Display.html?id=485766

for much more on this issue
T.

**Comment by kaplun** [comment]
Actually the 1st query is correct. While the second one is broken because the `-` is becoming part of the `author` tag.

Let's see if it is already fixed in Invenio master

**Comment by kaplun** [comment]
Superseeded by: inveniosoftware/invenio-query-parser#24
