### ISSUE TITLE
bibcheck filter_collection limitation

### ISSUE THREAD

**Issue by tsgit** [inspirehep/invenio#273]
Hi,

I realized that "filter_collection = HEP" in the rules.cfg only takes effect if there is some search expression. I don't think that's obvious. I wanted to run a rule on all HEP records.
The workaround is of course to filter_pattern = 980__a:HEP

Is that intended behavior or implementation oversight?
T

**Comment by kaplun** [comment]
That was a bug. That I have just fixed yesterday :-) you can now just specify the collection and it will do the right thing

**Comment by kaplun** [comment]
Fixed in 419459cfa64c497d99e8cbb7a223ac65c1b570a2
