### ISSUE TITLE
author tokenizer for names without comma

### ISSUE THREAD

**Issue by tsgit** [inspirehep/invenio#328]
there a several legitimate single name authors in Inspire

the author tokenizer assumes that there is a comma separating lastname and other name parts. this fails to correctly tokenize single name authors.

see this RT ticket
https://rt.inspirehep.net/Ticket/Display.html?id=471092

the name in 100__q does not contain a comma

`001340243 100__ $$aChang, Tsung-Sui$$qZhāng Zōng Suì$$q张宗燧$$uBeijing Normal U.`

a suggested fix:

 https://github.com/inspirehep/invenio/compare/prod...tsgit:authortokenizer

I note that instead of the else clause one could skip the entire conditional and use split as is, but this makes the intention clearer

Since this affects the author index as a whole, I invite comments on this.

**Comment by kaplun** [comment]
:+1: I see no inherent issues with your implementation.

**Comment by tsgit** [comment]
deployed
