### ISSUE TITLE
bibrank selfcites arbitrary author limit

### ISSUE THREAD

**Issue by tsgit** [inspirehep/invenio#364]
https://rt.inspirehep.net/Ticket/Display.html?id=612242

there is an undocumented limit (magical raw number in code) on number of authors on a record taken into consideration for the selfcitation analysis.

this affects searches like  https://inspirehep.net/search?p=referstox%3Arecid%3A1374998

where several obvious self-citations are returned -- without obvious reason. clearly this is suboptimal.

also, this https://inspirehep.net/search?p=refersto%3Arecid%3A1374998+-referstox%3Arecid%3A1374998
doesn't make any sense

record/1374998 has 33 authors which is over the limit of 20 used for selfcitation exclusion

Somewhere the line has to be drawn between individually authored records and collaboration papers and there are a few questions:

* what's a reasonable limit of number of authors on a record to take into account for self citation analysis
(also keep performance in mind)
* how are collaborations, working groups, etc. handled
* how is this going to be presented to the user in the UI

there already is code to specifically handle collaborations which are recognized as such from the MARC tags

I note that changing this magical number will require a global rerun of bibrank -w selfcitation which will take many days and affect many search results, so we need to settle this with an eye on consistency and persistence

a quick "fix" is something along these lines:

https://github.com/tsgit/invenio/commit/cb43a68f9ea1a5ae6da8b24e19920b43d9344d73

**Comment by kaplun** [comment]
@tsgit thanks a lot for this archaeology work! Indeed this magic number was completely non-transparent to users and developers. 

I believe the real fix would be not to return an empty set, but just the first N authors.

For a citation to be considered a self-citation it suffice that at least 1 author belongs to the intersection (something that is impossible to be done with the current returning of empty set).

**Comment by tsgit** [comment]
https://github.com/inspirehep/invenio/pull/365
