### ISSUE TITLE
backport improvements to refextract

### ISSUE THREAD

**Issue by michamos** [inspirehep/invenio#375]
- [ ] inspirehep/refextract#15
- [ ] inspirehep/refextract#18

(This seems to be the right place for it instead of inspirehep/inspire#256)

**Comment by tsgit** [comment]
@michamos are you going to do the backporting?

**Comment by michamos** [comment]
@kaplun said he would do it, but I am willing to help if possible

**Comment by kaplun** [comment]
OK, I was trying to give it a try. Basically one has to apply this patch:
https://gist.github.com/kaplun/a5071c51bcea9ca2d6609555c4262be7

However it is quite tricky. Many new files are specific to independent refextract and can be ignored. But other are more risky.

@michamos maybe for you it's quick to just try to apply it and see what can be quickly skipped?

**Comment by kaplun** [comment]
Alternatively, we might simply just install independent refextract on legacy and have the invenio one just call it?

**Comment by michamos** [comment]
It looks very hard to backport all changes, so I am closing this. I did #395 which, besides rewriting paths, already required doing all changes to python code by hand because of stylistic changes. So probably better to try to run reference extraction on labs ASAP.
