### ISSUE TITLE
Sorting by 'cited by' in the search returns over 9000 results

### ISSUE THREAD

**Issue by kaplun** [inspirehep/invenio#432]
@dset0x commented on [Fri Feb 06 2015](https://github.com/inspirehep/inspire/issues/70)

This is the simplest search that triggers returning every result in a single page:
https://inspirehep.net/search?ln=en&ln=en&p=&of=hb&action_search=Search&sf=earliestdate&so=d&rm=citation&rg=25&sc=0

Please try not to abuse this issue.

---

@MSusik commented on [Fri Feb 06 2015](https://github.com/inspirehep/inspire/issues/70#issuecomment-73275324)

Wrong title. Returns over 1000000 results.

---

@PXke commented on [Fri Feb 06 2015](https://github.com/inspirehep/inspire/issues/70#issuecomment-73281567)

It is due to Bibrank if I am right, we fixed it at TIND I think.

---

@kaplun commented on [Fri Aug 14 2015](https://github.com/inspirehep/inspire/issues/70#issuecomment-131115621)

Uh! @PXke Have you sent a patch upstream?

---

@PXke commented on [Fri Aug 14 2015](https://github.com/inspirehep/inspire/issues/70#issuecomment-131119169)

No at my knowledge, @Aurdan @blixhavn @Audub ?

---

@kaplun commented on [Tue Nov 21 2017](https://github.com/inspirehep/inspire/issues/70#issuecomment-345960886)

@tsgit this is still true and can bring INSPIRE to its knee. Maybe you can have a look at it?

**Comment by tsgit** [comment]
mmh, the sample URL above returns 25 records for me as it should


commit 5490639b122b727d2df2f78f8b79415dc049d26c                                                                                             
Author: Thorsten Schwander <thorsten.schwander@gmail.com>                                                                                   
Date:   Tue Nov 22 20:10:10 2016 -0700                                                                                                       
                                                                                                                                             
    WebSearch: fix pagination when ranking                                                                                                   
                                                                                                                                              
        * sorting results by citations is properly sliced                                                                                      
          via rg and jrec                                                                                                                      
                                                                                                                                                 
    Signed-off-by: Thorsten Schwander <thorsten.schwander@gmail.com>
